### ISSUE TITLE
Bug:后端启动，网页访问报错  java -jar  -Dloader.path=./lib -Dchatgpt.apiKey=xxxx chat2db-server-start.jar

### ISSUE THREAD

**Issue by Aruen24** [chat2db/Chat2DB#1029]
### Chat2DB Version

3.1.15

### Describe the bug

2023-12-27 09:38:37.372 ERROR 1808036 --- [io-10821-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]   .175 :  | Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers
        at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869)
        at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077)
        at org.thymeleaf.spring6.view.ThymeleafView.renderFragment(ThymeleafView.java:372)
        at org.thymeleaf.spring6.view.ThymeleafView.render(ThymeleafView.java:192)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1415)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1159)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1098)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at ai.chat2db.server.start.config.interceptor.CorsFilter.doFilter(CorsFilter.java:37)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
        at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at ai.chat2db.server.start.log.LogOncePerRequestFilter.doFilterInternal(LogOncePerRequestFilter.java:32)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:842)

网页端访问http://localhost:10821
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Dec 27 09:48:20 UTC 2023
There was an unexpected error (type=Not Found, status=404).

**Comment by shanhexi** [comment]
正式版的端口号为。10824

**Comment by Aruen24** [comment]
> 正式版的端口号为。10824

2023-12-28 01:17:07.964  INFO 1809943 --- [           main] ai.chat2db.server.start.Application     .51 :  | Starting Application v2.0.0-SNAPSHOT using Java 17.0.9 with PID 1809943 (/Data2/wyw/Chat2DB/chat2db-server/chat2db-server-start/target/chat2db-server-start.jar started by wyw in /Data2/wyw/Chat2DB/chat2db-server/chat2db-server-start/target)
2023-12-28 01:17:07.970  INFO 1809943 --- [           main] ai.chat2db.server.start.Application     .639 :  | The following 1 profile is active: "dev"
2023-12-28 01:17:10.048  INFO 1809943 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer .108 :  | Tomcat initialized with port(s): 10821 (http)
2023-12-28 01:17:10.060  INFO 1809943 --- [           main] o.apache.catalina.core.StandardService  .173 :  | Starting service [Tomcat]
2023-12-28 01:17:10.061  INFO 1809943 --- [           main] o.apache.catalina.core.StandardEngine   .173 :  | Starting Servlet engine: [Apache Tomcat/10.1.8]
2023-12-28 01:17:10.144  INFO 1809943 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]      .173 :  | Initializing Spring embedded WebApplicationContext
2023-12-28 01:17:10.144  INFO 1809943 --- [           main] w.s.c.ServletWebServerApplicationContext.291 :  | Root WebApplicationContext: initialization completed in 2110 ms
2023-12-28 01:17:10.350  INFO 1809943 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer .220 :  | Tomcat started on port(s): 10821 (http) with context path ''
2023-12-28 01:17:10.419  INFO 1809943 --- [           main] ai.chat2db.server.start.Application     .57 :  | Started Application in 3.182 seconds (process running for 3.843)
2023-12-28 01:17:30.048  INFO 1809943 --- [io-10821-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]      .173 :  | Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-12-28 01:17:30.049  INFO 1809943 --- [io-10821-exec-1] o.s.web.servlet.DispatcherServlet       .532 :  | Initializing Servlet 'dispatcherServlet'
2023-12-28 01:17:30.434  WARN 1809943 --- [io-10821-exec-1] o.thymeleaf.templatemode.TemplateMode   .92 :  | [THYMELEAF][http-nio-10821-exec-1] Unknown Template Mode 'HTML5'. Must be one of: 'HTML', 'XML', 'TEXT', 'JAVASCRIPT', 'CSS', 'RAW'. Using default Template Mode 'HTML'.
2023-12-28 01:17:30.462  INFO 1809943 --- [io-10821-exec-1] o.s.web.servlet.DispatcherServlet       .554 :  | Completed initialization in 412 ms
2023-12-28 01:17:31.388  WARN 1809943 --- [io-10821-exec-1] a.c.s.tools.common.util.ConfigUtils     .55 : d9e06289d04546feb520071fd7ffeadd | VERSION_FILE is null
2023-12-28 01:17:31.623  INFO 1809943 --- [io-10821-exec-1] com.zaxxer.hikari.HikariDataSource      .110 : d9e06289d04546feb520071fd7ffeadd | HikariPool-1 - Starting...
2023-12-28 01:17:32.073  INFO 1809943 --- [io-10821-exec-1] com.zaxxer.hikari.pool.HikariPool       .565 : d9e06289d04546feb520071fd7ffeadd | HikariPool-1 - Added connection conn0: url=jdbc:h2:file:~/.chat2db/db/chat2db_dev user=
2023-12-28 01:17:32.075  INFO 1809943 --- [io-10821-exec-1] com.zaxxer.hikari.HikariDataSource      .123 : d9e06289d04546feb520071fd7ffeadd | HikariPool-1 - Start completed.
2023-12-28 01:17:32.200  INFO 1809943 --- [io-10821-exec-1] o.f.core.internal.command.DbValidate    .36 : d9e06289d04546feb520071fd7ffeadd | Successfully validated 16 migrations (execution time 00:00.067s)
2023-12-28 01:17:32.211  INFO 1809943 --- [io-10821-exec-1] o.f.core.internal.command.DbMigrate     .36 : d9e06289d04546feb520071fd7ffeadd | Current version of schema "PUBLIC": 2.1.8
2023-12-28 01:17:32.212  INFO 1809943 --- [io-10821-exec-1] o.f.core.internal.command.DbMigrate     .36 : d9e06289d04546feb520071fd7ffeadd | Schema "PUBLIC" is up to date. No migration necessary.
2023-12-28 01:17:32.241  INFO 1809943 --- [io-10821-exec-1] a.c.s.tools.common.util.ConfigUtils     .84 : d9e06289d04546feb520071fd7ffeadd | set config:{"jwtSecretKey":"d702373a2f814d4ab0209ad3178eac41","systemUuid":"7fbcf8c220cf4b5db076098e2e43ae72"}
2023-12-28 01:17:32.543 ERROR 1809943 --- [io-10821-exec-1] org.thymeleaf.TemplateEngine            .1141 : d9e06289d04546feb520071fd7ffeadd | [THYMELEAF][http-nio-10821-exec-1] Exception processing template "index": Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers

启动是这样的，访问10824，无法访问此网站

**Comment by RYiHui** [comment]
我也遇到了同样的问题，请问 @Aruen24 你是如何解决的
