### ISSUE TITLE
Bug: docker starts the latest version abnormally

### ISSUE THREAD

**Issue by zhanbinHo** [chat2db/Chat2DB#1031]
### Chat2DB Version

latest

### Describe the bug

2023-12-27 10:26:30.770  INFO 1 --- [io-10824-exec-1] c.s.w.s.e.EasyControllerExceptionHandler.100 : a74d3600be0f42a1b3e67b3355ab01f0 | 发生ModelAndView业务异常/:ModelAndView [view="redirect:/login?callback=/"; model=null]

ai.chat2db.server.tools.common.exception.RedirectBusinessException: common.redirect
	at ai.chat2db.server.web.start.config.config.Chat2dbWebMvcConfigurer$2.preHandle(Chat2dbWebMvcConfigurer.java:153)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:146)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1076)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at ai.chat2db.server.web.start.config.interceptor.CorsFilter.doFilter(CorsFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
	at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at ai.chat2db.server.web.start.log.LogOncePerRequestFilter.doFilterInternal(LogOncePerRequestFilter.java:32)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-12-27 10:26:31.232 ERROR 1 --- [io-10824-exec-2] org.thymeleaf.TemplateEngine            .1141 : 1d92460def97488d95fb2e07200fdcbb | [THYMELEAF][http-nio-10824-exec-2] Exception processing template "index": Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869)
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077)
	at org.thymeleaf.spring6.view.ThymeleafView.renderFragment(ThymeleafView.java:372)
	at org.thymeleaf.spring6.view.ThymeleafView.render(ThymeleafView.java:192)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1415)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1159)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1098)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at ai.chat2db.server.web.start.config.interceptor.CorsFilter.doFilter(CorsFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
	at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at ai.chat2db.server.web.start.log.LogOncePerRequestFilter.doFilterInternal(LogOncePerRequestFilter.java:32)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-12-27 10:26:31.236 ERROR 1 --- [io-10824-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]   .175 :  | Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869)
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077)
	at org.thymeleaf.spring6.view.ThymeleafView.renderFragment(ThymeleafView.java:372)
	at org.thymeleaf.spring6.view.ThymeleafView.render(ThymeleafView.java:192)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1415)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1159)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1098)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at ai.chat2db.server.web.start.config.interceptor.CorsFilter.doFilter(CorsFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
	at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at ai.chat2db.server.web.start.log.LogOncePerRequestFilter.doFilterInternal(LogOncePerRequestFilter.java:32)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zhanbinHo** [comment]
启动命令用的是这个： docker run --name=chat2db -ti -p 10824:10824 -v ~/.chat2db-docker:/root/.chat2db  chat2db/chat2db:latest

**Comment by Arronlong** [comment]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Dec 28 03:33:33 UTC 2023
There was an unexpected error (type=Internal Server Error, status=500).

**Comment by Arronlong** [comment]
> 启动命令用的是这个： docker run --name=chat2db -ti -p 10824:10824 -v ~/.chat2db-docker:/root/.chat2db chat2db/chat2db:latest

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Dec 28 03:33:33 UTC 2023
There was an unexpected error (type=Internal Server Error, status=500).

**Comment by xiandan-erizo** [comment]
同问，Mark
![image](https://github.com/chat2db/Chat2DB/assets/23250774/ba47d56a-e04a-458a-b6af-e3e75043a47b)
![image](https://github.com/chat2db/Chat2DB/assets/23250774/cbe0eef6-96db-4ace-b91f-41e8bd3e9fb2)

**Comment by GuXiaozhou** [comment]
同样的问题  怎么解决的

**Comment by Arronlong** [comment]
把docker里的jar拿出来看了一下，原来是没有把前端打包进去.....话说你们都不做测试的吗？？？

自行解决方案：

1. 把docker里的jar文件copy到宿主机上
```
docker cp chat2db:/app/chat2db-server-web-start.jar ./chat2db-server-web-start.jar
```

2. 下载到本地
```
sz chat2db-server-web-start.jar
```
3. 下载对应版本的源码，zip格式，
4. 进入到chat2db-client，自行打包
```
yarn
npm run build:web:prod
```
5. 复制dist目录到跟jar同级目录下
6. 为jar添加打包的前端文件
```
mv chat2db-server-web-start.jar chat2db-server-web-start.jar.zip
unzip  chat2db-server-web-start.jar.zip

cp -r dist ./BOOT-INF/classes/static/front 
cp dist/index.html ./BOOT-INF/classes/thymeleaf/

jar -cfM0 chat2db-server-web-start.jar BOOT-INF/ META-INF/ org/

rm -rf BOOT-INF/ META-INF/ org/ chat2db-server-web-start.jar.zip
```
7. 上传新打包的jar到服务器
8. 更新jar到docker
```
docker cp ./chat2db-server-web-start.jar chat2db:/app/chat2db-server-web-start.jar
```
9. 重启docker
```
docker restart chat2db
```
10.访问页面，over！

**Comment by shanhexi** [comment]
> 把docker里的jar拿出来看了一下，原来是没有把前端打包进去.....话说你们都不做测试的吗？？？
> 
> 自行解决方案：
> 
> 1. 把docker里的jar文件copy到宿主机上
> 
> ```
> docker cp chat2db:/app/chat2db-server-web-start.jar ./chat2db-server-web-start.jar
> ```
> 
> 2. 下载到本地
> 
> ```
> sz chat2db-server-web-start.jar
> ```
> 
> 3. 下载对应版本的源码，zip格式，
> 4. 进入到chat2db-client，自行打包
> 
> ```
> yarn
> npm run build:web:prod
> ```
> 
> 5. 复制dist目录到跟jar同级目录下
> 6. 为jar添加打包的前端文件
> 
> ```
> mv chat2db-server-web-start.jar chat2db-server-web-start.jar.zip
> unzip  chat2db-server-web-start.jar.zip
> 
> cp -r dist ./BOOT-INF/classes/static/front 
> cp dist/index.html ./BOOT-INF/classes/thymeleaf/
> 
> jar -cfM0 chat2db-server-web-start.jar BOOT-INF/ META-INF/ org/
> 
> rm -rf BOOT-INF/ META-INF/ org/ chat2db-server-web-start.jar.zip
> ```
> 
> 7. 上传新打包的jar到服务器
> 8. 更新jar到docker
> 
> ```
> docker cp ./chat2db-server-web-start.jar chat2db:/app/chat2db-server-web-start.jar
> ```
> 
> 9. 重启docker
> 
> ```
> docker restart chat2db
> ```
> 
> 10.访问页面，over！

额 已经解了 3.1.18

**Comment by Arronlong** [comment]
> > 把docker里的jar拿出来看了一下，原来是没有把前端打包进去.....话说你们都不做测试的吗？？？
> > 自行解决方案：
> > 
> > 1. 把docker里的jar文件copy到宿主机上
> > 
> > ```
> > docker cp chat2db:/app/chat2db-server-web-start.jar ./chat2db-server-web-start.jar
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. 下载到本地
> > 
> > ```
> > sz chat2db-server-web-start.jar
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. 下载对应版本的源码，zip格式，
> > 4. 进入到chat2db-client，自行打包
> > 
> > ```
> > yarn
> > npm run build:web:prod
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 5. 复制dist目录到跟jar同级目录下
> > 6. 为jar添加打包的前端文件
> > 
> > ```
> > mv chat2db-server-web-start.jar chat2db-server-web-start.jar.zip
> > unzip  chat2db-server-web-start.jar.zip
> > 
> > cp -r dist ./BOOT-INF/classes/static/front 
> > cp dist/index.html ./BOOT-INF/classes/thymeleaf/
> > 
> > jar -cfM0 chat2db-server-web-start.jar BOOT-INF/ META-INF/ org/
> > 
> > rm -rf BOOT-INF/ META-INF/ org/ chat2db-server-web-start.jar.zip
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 7. 上传新打包的jar到服务器
> > 8. 更新jar到docker
> > 
> > ```
> > docker cp ./chat2db-server-web-start.jar chat2db:/app/chat2db-server-web-start.jar
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 9. 重启docker
> > 
> > ```
> > docker restart chat2db
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 10.访问页面，over！
> 
> 额 已经解了 3.1.18

好吧，1分钟前上传了新镜像...

**Comment by shanhexi** [comment]
> 同样的问题 怎么解决的

拉一下最新的镜像已解决

**Comment by shanhexi** [comment]
> > > 把docker里的jar拿出来看了一下，原来是没有把前端打包进去.....话说你们都不做测试的吗？？？
> > > 自行解决方案：
> > > 
> > > 1. 把docker里的jar文件copy到宿主机上
> > > 
> > > ```
> > > docker cp chat2db:/app/chat2db-server-web-start.jar ./chat2db-server-web-start.jar
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 2. 下载到本地
> > > 
> > > ```
> > > sz chat2db-server-web-start.jar
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 3. 下载对应版本的源码，zip格式，
> > > 4. 进入到chat2db-client，自行打包
> > > 
> > > ```
> > > yarn
> > > npm run build:web:prod
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 5. 复制dist目录到跟jar同级目录下
> > > 6. 为jar添加打包的前端文件
> > > 
> > > ```
> > > mv chat2db-server-web-start.jar chat2db-server-web-start.jar.zip
> > > unzip  chat2db-server-web-start.jar.zip
> > > 
> > > cp -r dist ./BOOT-INF/classes/static/front 
> > > cp dist/index.html ./BOOT-INF/classes/thymeleaf/
> > > 
> > > jar -cfM0 chat2db-server-web-start.jar BOOT-INF/ META-INF/ org/
> > > 
> > > rm -rf BOOT-INF/ META-INF/ org/ chat2db-server-web-start.jar.zip
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 7. 上传新打包的jar到服务器
> > > 8. 更新jar到docker
> > > 
> > > ```
> > > docker cp ./chat2db-server-web-start.jar chat2db:/app/chat2db-server-web-start.jar
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 9. 重启docker
> > > 
> > > ```
> > > docker restart chat2db
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 10.访问页面，over！
> > 
> > 
> > 额 已经解了 3.1.18
> 
> 好吧，1分钟前上传了新镜像...

试一下看有问题么，好了回复下

**Comment by Arronlong** [comment]
> > > > 把docker里的jar拿出来看了一下，原来是没有把前端打包进去.....话说你们都不做测试的吗？？？
> > > > 自行解决方案：
> > > > 
> > > > 1. 把docker里的jar文件copy到宿主机上
> > > > 
> > > > ```
> > > > docker cp chat2db:/app/chat2db-server-web-start.jar ./chat2db-server-web-start.jar
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 
> > > > 2. 下载到本地
> > > > 
> > > > ```
> > > > sz chat2db-server-web-start.jar
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 
> > > > 3. 下载对应版本的源码，zip格式，
> > > > 4. 进入到chat2db-client，自行打包
> > > > 
> > > > ```
> > > > yarn
> > > > npm run build:web:prod
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 
> > > > 5. 复制dist目录到跟jar同级目录下
> > > > 6. 为jar添加打包的前端文件
> > > > 
> > > > ```
> > > > mv chat2db-server-web-start.jar chat2db-server-web-start.jar.zip
> > > > unzip  chat2db-server-web-start.jar.zip
> > > > 
> > > > cp -r dist ./BOOT-INF/classes/static/front 
> > > > cp dist/index.html ./BOOT-INF/classes/thymeleaf/
> > > > 
> > > > jar -cfM0 chat2db-server-web-start.jar BOOT-INF/ META-INF/ org/
> > > > 
> > > > rm -rf BOOT-INF/ META-INF/ org/ chat2db-server-web-start.jar.zip
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 
> > > > 7. 上传新打包的jar到服务器
> > > > 8. 更新jar到docker
> > > > 
> > > > ```
> > > > docker cp ./chat2db-server-web-start.jar chat2db:/app/chat2db-server-web-start.jar
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 
> > > > 9. 重启docker
> > > > 
> > > > ```
> > > > docker restart chat2db
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 10.访问页面，over！
> > > 
> > > 
> > > 额 已经解了 3.1.18
> > 
> > 
> > 好吧，1分钟前上传了新镜像...
> 
> 试一下看有问题么，好了回复下

ok了

**Comment by miahemu** [comment]
> 访问页面的地址是什么

localhost:10824
详情链接：https://docs.chat2db.ai/zh-CN/docs/question/private-deployment
