### ISSUE TITLE
Bug: 部署报错NoClassDefFoundError: Could not initialize class ai.chat2db.server.domain.repository.Dbutils

### ISSUE THREAD

**Issue by zhuairen** [chat2db/Chat2DB#1200]
### Chat2DB Version

3.1.18

### Describe the bug

Caused by: java.lang.NoClassDefFoundError: Could not initialize class ai.chat2db.server.domain.repository.Dbutils
	at ai.chat2db.server.start.config.config.Chat2dbWebMvcConfigurer$1.preHandle(Chat2dbWebMvcConfigurer.java:70)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:146)

复现步骤；
FROM ubuntu:latest
CMD ["tail", "-f", "/dev/null"]

进入linux安装3.1.18版本
jdk版本：17.0.1
java -jar chat2db-server-start.jar

访问ip:port报错

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.
