### ISSUE TITLE
Bug: 无法使用OPENAI的服务

### ISSUE THREAD

**Issue by ByeByeChen** [chat2db/Chat2DB#1201]
### Chat2DB Version

3.1.19

### Describe the bug

2024-03-06 16:08:54.689  INFO 14661 --- [[sd.ai:30003/](http://sd.ai:30003/)...] .s.w.a.c.a.o.l.OpenAIEventSourceListener.38 :  | OpenAI建立sse连接...
2024-03-06 16:08:54.690  INFO 14661 --- [[sd.ai:30003/](http://sd.ai:30003/)...] .s.w.a.c.a.o.l.OpenAIEventSourceListener.47 :  | OpenAI返回数据：{"id": "chatcmpl-9654e8b1-674d-4c1f-8220-867abd4e1834", "choices": [{"delta": {"content": "", "function_call": null, "role": "assistant", "tool_calls": null}, "finish_reason": null, "index": 0, "logprobs": null}], "created": 1709712578, "model": "gpt-3.5-turbo", "object": "chat.completion.chunk", "system_fingerprint": null}
2024-03-06 16:08:56.019  INFO 14661 --- [[sd.ai:30003/](http://sd.ai:30003/)...] .s.w.a.c.a.o.l.OpenAIEventSourceListener.47 :  | OpenAI返回数据：{"id": "chatcmpl-9654e8b1-674d-4c1f-8220-867abd4e1834", "choices": [{"delta": {"content": "\u62b1\u6b49", "function_call": null, "role": null, "tool_calls": null}, "finish_reason": null, "index": 0, "logprobs": null}], "created": 1709712579, "model": "gpt-3.5-turbo", "object": "chat.completion.chunk", "system_fingerprint": null}
2024-03-06 16:08:56.021 ERROR 14661 --- [[sd.ai:30003/](http://sd.ai:30003/)...] .s.w.a.c.a.o.l.OpenAIEventSourceListener.103 :  | OpenAI  sse连接异常data：

com.fasterxml.jackson.databind.JsonMappingException: role is marked non-null but is null
 at [Source: (String)"{"id": "chatcmpl-9654e8b1-674d-4c1f-8220-867abd4e1834", "choices": [{"delta": {"content": "\u62b1\u6b49", "function_call": null, "role": null, "tool_calls": null}, "finish_reason": null, "index": 0, "logprobs": null}], "created": 1709712579, "model": "gpt-3.5-turbo", "object": "chat.completion.chunk", "system_fingerprint": null}"; line: 1, column: 138] (through reference chain: ai.chat2db.server.web.api.controller.ai.response.ChatCompletionResponse["choices"]->java.util.ArrayList[0]->ai.chat2db.server.web.api.controller.ai.response.ChatChoice["delta"]->com.unfbx.chatgpt.entity.chat.Message["role"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:276)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:630)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:618)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:143)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at ai.chat2db.server.web.api.controller.ai.openai.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:60)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: role is marked non-null but is null
	at com.unfbx.chatgpt.entity.chat.Message.setRole(Message.java:16)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:141)
	... 25 common frames omitted

2024-03-06 16:08:56.024  INFO 14661 --- [io-10821-exec-6] a.chat2db.server.start.log.EasyLogSink  .73 :  | http : GET|/api/ai/chat?message=%E4%BD%A0%E5%A5%BD&promptType=NL_2_SQL&dataSourceId=2|1352||text/event-stream:[8]
2024-03-06 16:08:56.025  INFO 14661 --- [io-10821-exec-6] a.c.s.w.a.controller.ai.ChatController  .531 :  | 2024-03-06T16:08:56.025007717, uid#OPENAIa163cdf6-56a2-48ea-a398-f39946bcd561, on completion

**Comment by ByeByeChen** [comment]
![20240306-161530](https://github.com/chat2db/Chat2DB/assets/31759166/b50b7cc4-b094-4833-a3dd-119e1953163a)

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.
