### ISSUE TITLE
Bug: 使用中偶发白屏

### ISSUE THREAD

**Issue by caiqingyuan95** [chat2db/Chat2DB#1292]
### Chat2DB Version

v3.1.19

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/41459110/b10011ba-eaca-4e93-8b6b-971586945bbd)
控制台输出报错为：
umi.b8140814.js:30 SyntaxError: Invalid regular expression: /t_third)/: Unmatched ')'
    at new RegExp (<anonymous>)
    at Dr (p__main__index.d93bb28f.async.js:9:20655)
    at r (p__main__index.d93bb28f.async.js:9:20802)
    at p__main__index.d93bb28f.async.js:9:20958
    at Array.forEach (<anonymous>)
    at Di (p__main__index.d93bb28f.async.js:9:20931)
    at p__main__index.d93bb28f.async.js:9:21905
    at zi (umi.b8140814.js:30:24458)
    at du (umi.b8140814.js:30:43067)
    at ef (umi.b8140814.js:30:41839)
Rs @ umi.b8140814.js:30
umi.b8140814.js:28 Uncaught SyntaxError: Invalid regular expression: /t_third)/: Unmatched ')'
    at new RegExp (<anonymous>)
    at Dr (p__main__index.d93bb28f.async.js:9:20655)
    at r (p__main__index.d93bb28f.async.js:9:20802)
    at p__main__index.d93bb28f.async.js:9:20958
    at Array.forEach (<anonymous>)
    at Di (p__main__index.d93bb28f.async.js:9:20931)
    at p__main__index.d93bb28f.async.js:9:21905
    at zi (umi.b8140814.js:30:24458)
    at du (umi.b8140814.js:30:43067)
    at ef (umi.b8140814.js:30:41839)

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.
