### ISSUE TITLE
Bug: CustomAi 设置之后总是报异常  

### ISSUE THREAD

**Issue by heming79** [chat2db/Chat2DB#1400]
### Chat2DB Version

 Chat2DB3.1.22

### Describe the bug

Bug: CustomAi 设置之后总是报异常  

2024-05-23 03:59:53.827 ERROR 1 --- [io-10824-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]   .175 :  | Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: BusinessException(super=ai.chat2db.server.tools.common.exception.ParamBusinessException: common.paramDetailError, code=common.paramDetailError, args=[dataSourceId])] with root cause

ai.chat2db.server.tools.common.exception.ParamBusinessException: common.paramDetailError
        at ai.chat2db.server.web.api.aspect.ConnectionInfoHandler.toInfo(ConnectionInfoHandler.java:72)
        at ai.chat2db.server.web.api.aspect.ConnectionInfoHandler.connectionInfoHandler(ConnectionInfoHandler.java:49)
        at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
        at ai.chat2db.server.web.api.controller.ai.ChatController$$SpringCGLIB$$0.completions(<generated>)
        at jdk.internal.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at ai.chat2db.server.web.start.config.interceptor.CorsFilter.doFilter(CorsFilter.java:33)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
        at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at ai.chat2db.server.web.start.log.LogOncePerRequestFilter.doFilterInternal(LogOncePerRequestFilter.java:32)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by heming79** [comment]
调用智谱ai也报错  
### SQL input: 生成查询表chat_view 3条样本数据sql
2024-05-23 05:19:27.216  INFO 1 --- [io-10824-exec-5] .c.s.w.a.c.a.z.c.ZhipuChatAIStreamClient.216 : 6c887d2bbe0e455592c8d406ec275ceb | finish invoking zhipu chat ai
2024-05-23 05:19:27.611 ERROR 1 --- [bigmodel.cn/...] a.c.a.z.l.ZhipuChatAIEventSourceListener.116 :  | Zhipu Chat AI sse response：
2024-05-23 05:19:27.613  INFO 1 --- [io-10824-exec-1] a.c.server.web.start.log.EasyLogSink    .69 :  | http : GET|/api/ai/chat?message=%E7%94%9F%E6%88%90%E6%9F%A5%E8%AF%A2%E8%A1%A8chat_view+3%E6%9D%A1%E6%A0%B7%E6%9C%AC%E6%95%B0%E6%8D%AEsql&promptType=NL_2_SQL&dataSourceId=3&databaseName=dataease&tableNames=area_mapping|451||text/event-stream:[8]
2024-05-23 05:19:27.614  INFO 1 --- [io-10824-exec-1] a.c.s.w.a.controller.ai.ChatController  .531 :  | 2024-05-23T05:19:27.614097992, uid#ZHIPUAI6a3ddfbd-65c8-445f-bb2b-41ba03461abd, on completion

![image](https://github.com/chat2db/Chat2DB/assets/14069019/28c50671-eaaf-4c96-b57a-45fc659bd4fb)

**Comment by heming79** [comment]
服务器上命令行请求智谱ai是没问题的 。 
![image](https://github.com/chat2db/Chat2DB/assets/14069019/540e0c27-6fca-40aa-8318-ea0f0b0ddc9f)

**Comment by heming79** [comment]
另外使用文心一言的时候总报  ，请问调用文心使用的具体什么模型？ 
Wenxin chat AI error：{"error_code":17,"error_msg":"Open api daily request limit reached"}

**Comment by tmlx1990** [comment]
> 另外使用文心一言的时候总报 ，请问调用文心使用的具体什么模型？ Wenxin chat AI error：{"error_code":17,"error_msg":"Open api daily request limit reached"}

Open api daily request limit reached 你这个报错 应该是你的key超过每日请求上限了吧

**Comment by tmlx1990** [comment]
> 刚申请的 ，想知道用的哪个模型为什么会报请求上限， 都没有调用过。

你用的是开源版吗？开源版是你自己在设置里设置用哪个模型，并配置自己的key

**Comment by heming79** [comment]
是开源版 就这两个参数
![image](https://github.com/chat2db/Chat2DB/assets/14069019/0ee70043-cfa0-4629-9a01-f10401420e9f)

**Comment by tmlx1990** [comment]
> 是开源版 就这两个参数 ![image](https://private-user-images.githubusercontent.com/14069019/333431294-0ee70043-cfa0-4629-9a01-f10401420e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MjEwNDMsIm5iZiI6MTcxNjUyMDc0MywicGF0aCI6Ii8xNDA2OTAxOS8zMzM0MzEyOTQtMGVlNzAwNDMtY2ZhMC00NjI5LTlhMDEtZjEwNDAxNDIwZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAzMTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NjBkY2VmYmY2YzNkOTdlZTcwYWNlNTNiYTIzZTdmZjkwYjJlNWZmMmU1ODI3YjZhODY0NTFhNjAwODI5OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8sx6lrTZsWSxT9llPVxC5CZbuEBJDQi3fHit6naRl9A)

这个需要你自己确定你的文心一言ai的apikey的权限。

**Comment by heming79** [comment]
apikey 提供了  ， 不知道为什么提示limit  。如果填的是错的话 会提示apikey错误

**Comment by tmlx1990** [comment]
> apikey 提供了 ， 不知道为什么提示limit 。如果填的是错的话 会提示apikey错误

这个你需要联系文心一言，你要用他们的apikey需要问他们为什么报超过每日上限。这些是他们校验的。

**Comment by lxc00215** [comment]
我也有一个问题，我使用的是one-api 的接口，部署在我本地的电脑上。一般我的请求地址就是http://ip:3000,但是当我完成设置，点击应用按钮之后，请求地址的末尾会自动加上一个"/”,请求地址变成了 http://ip:3000/,多了一个斜杠我的one-api就无法请求到我的服务了，请问这个问题如何解决？

**Comment by wangaocheng** [comment]
> 我也有一个问题，我使用的是one-api 的接口，部署在我本地的电脑上。一般我的请求地址就是[http://ip:3000,但是当我完成设置，点击应用按钮之后，请求地址的末尾会自动加上一个"/”,请求地址变成了](http://ip:3000,%E4%BD%86%E6%98%AF%E5%BD%93%E6%88%91%E5%AE%8C%E6%88%90%E8%AE%BE%E7%BD%AE%EF%BC%8C%E7%82%B9%E5%87%BB%E5%BA%94%E7%94%A8%E6%8C%89%E9%92%AE%E4%B9%8B%E5%90%8E%EF%BC%8C%E8%AF%B7%E6%B1%82%E5%9C%B0%E5%9D%80%E7%9A%84%E6%9C%AB%E5%B0%BE%E4%BC%9A%E8%87%AA%E5%8A%A8%E5%8A%A0%E4%B8%8A%E4%B8%80%E4%B8%AA%22/%E2%80%9D,%E8%AF%B7%E6%B1%82%E5%9C%B0%E5%9D%80%E5%8F%98%E6%88%90%E4%BA%86) [http://ip:3000/,多了一个斜杠我的one-api就无法请求到我的服务了，请问这个问题如何解决？](http://ip:3000/,%E5%A4%9A%E4%BA%86%E4%B8%80%E4%B8%AA%E6%96%9C%E6%9D%A0%E6%88%91%E7%9A%84one-api%E5%B0%B1%E6%97%A0%E6%B3%95%E8%AF%B7%E6%B1%82%E5%88%B0%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E4%BA%86%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F)

我遇到了同样的问题。

**Comment by guoping1127** [comment]
我也是遇到这个问题，他嘎嘎报错

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.
