### ISSUE TITLE
Bug: There are Chinese characters on the path, and an error(NullPointerException) is reported

### ISSUE THREAD

**Issue by 789creator** [chat2db/Chat2DB#1445]
### Chat2DB Version

3.1.0

### Describe the bug

ai.chat2db.server.domain.repository.Dbutils#registryMapperXml

Exception in thread "Thread-0" java.lang.ExceptionInInitializerError
	at ai.chat2db.server.start.Application.lambda$main$0(Application.java:32)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local8>" is null
	at ai.chat2db.server.domain.repository.Dbutils.registryMapperXml(Dbutils.java:197)
	at ai.chat2db.server.domain.repository.Dbutils.before(Dbutils.java:96)
	at ai.chat2db.server.domain.repository.Dbutils.<clinit>(Dbutils.java:65)
	... 2 more

**Comment by tmlx1990** [comment]
您好，这是执行什么操作时候报的？

**Comment by 789creator** [comment]
> 您好，这是执行什么操作时候报的？

服务启动的时候。
Dbutils.registryMapperXml 方法里面加上URLDecoder.decode(path, StandardCharsets.UTF_8.toString())，就可以正常起来
![image](https://github.com/chat2db/Chat2DB/assets/20888158/2dee8ca6-3edb-404b-b7ab-ccb0b218baa7)

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.
