### ISSUE TITLE
Bug: hive connect fail: Peer indicated failure: Error validating the login

### ISSUE THREAD

**Issue by swtor-xing** [chat2db/Chat2DB#1504]
### Chat2DB Version

2.0.0-SNAPSHOT

### Describe the bug

Peer indicated failure: Error validating the login

The username and password have been set.

**Comment by swtor-xing** [comment]
java.sql.SQLException: Cannot create connection (Could not open client transport with JDBC Uri: jdbc:hive2:xxx : Peer indicated failure: Error validating the login)

        at ai.chat2db.spi.sql.IDriverManager.getConnection(IDriverManager.java:100)
        at ai.chat2db.spi.sql.IDriverManager.getConnection(IDriverManager.java:75)
        at ai.chat2db.spi.util.JdbcUtils.testConnect(JdbcUtils.java:162)
        at ai.chat2db.server.domain.core.impl.DataSourceServiceImpl.preConnect(DataSourceServiceImpl.java:255)
        at ai.chat2db.server.web.api.controller.data.source.DataSourceController.preConnect(DataSourceController.java:91)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.
