### ISSUE TITLE
Oracle的PDB无法打开链接. 提示错误, 但是同事非PDB是可以的

### ISSUE THREAD

**Issue by jinanxiaolaohu** [chat2db/Chat2DB#158]
common.systemError: An exception occurs, you can view the exception details in the log in the help menu. If you can't fix it, you can subscribe to the WeChat public account Text2SQL to consult for help

只有PDB有这个问题, 需要处理一下. 

ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:854)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
	at ai.chat2db.spi.sql.IDriverManager.getConnection(IDriverManager.java:81)
	at ai.chat2db.spi.sql.IDriverManager.getConnection(IDriverManager.java:66)
	at ai.chat2db.spi.sql.Chat2DBContext.getConnect(Chat2DBContext.java:154)
	at ai.chat2db.spi.sql.Chat2DBContext.setConnectInfoThreadLocal(Chat2DBContext.java:111)
	... 75 common frames omitted
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:284)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:340)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1596)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:588)
	... 83 common frames omitted

2023-07-04 22:50:01.168  INFO 11584 --- [http-nio-127.0.0.1-10824-exec-4] a.chat2db.server.start.log.EasyLogSink  .67 : a0b86370-52d2-4fb7-b23c-13e53233f2fb | http : GET|/api/rdb/ddl/database_schema_list?dataSourceId=4|19||{"success":false,"errorCode":"common.systemError","errorMessage":"An exception occurs, you can view the exception details in the log in the help menu. If you can't fix it, you can subscribe to the WeChat public account Text2SQL to consult for help","traceId":null}

**Comment by robinji0** [comment]
marked in #407
