### ISSUE TITLE
Bug: 连接数据库直接报错

### ISSUE THREAD

**Issue by FireheadSleep** [chat2db/Chat2DB#177]
### Chat2DB Version

2.0.1

### Describe the bug

报错提示是：
java.lang.RuntimeException: getConnect error
	at ai.chat2db.spi.sql.Chat2DBContext.setConnectInfoThreadLocal(Chat2DBContext.java:135)
	at ai.chat2db.spi.sql.Chat2DBContext.putContext(Chat2DBContext.java:84)
	at ai.chat2db.server.web.api.aspect.ConnectionInfoHandler.connectionInfoHandler(ConnectionInfoHandler.java:47)
	at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

具体原因是：
Caused by: java.lang.NullPointerException: Cannot invoke "ai.chat2db.spi.model.SSHInfo.setRHost(String)" because "ssh" is null
	at ai.chat2db.spi.sql.Chat2DBContext.setConnectInfoThreadLocal(Chat2DBContext.java:99)
	... 76 common frames omitted
点测试按钮正常：
![image](https://github.com/chat2db/Chat2DB/assets/102341803/9ea2cbc1-f176-40d0-b347-625262a6900a)
点击保存就提示报错：
![image](https://github.com/chat2db/Chat2DB/assets/102341803/e37ede82-000d-4495-ab58-20f624d7294c)

**Comment by zeropl** [comment]
想通的问题，你解决了吗

**Comment by FireheadSleep** [comment]
> 想通的问题，你解决了吗

没有，暂时先用dbeaver了

**Comment by diguoyihao** [comment]
相同的问题，你解决了吗

**Comment by jipengfei-jpf** [comment]
2.0.2已经解决

**Comment by BruceCham** [comment]
> 

2.0.5 mac Intel 还是报错，无法连接
