### ISSUE TITLE
Bug: 无法使用java -jar 执行

### ISSUE THREAD

**Issue by mkuiwu** [chat2db/Chat2DB#316]
### Chat2DB Version

2.0.5 jar版本

### Describe the bug

我的java版本：
java -version                                                                                                                                                                                
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7)
OpenJDK 64-Bit Server VM (build 17.0.7+7, mixed mode)

解压后的文件：
 ls                                                                                                                                                                                           
chat2db-server-start.jar  chat.log         ITEM_IMAGE-1920152731-68aad8cc5ba14f7fb086654ef7e1267f.jpg  jbr_jcef-17.0.6-linux-x64-b829.5.tar.gz
chat2db-server-start.zip  DataGrip-2023.2  jbr_jcef-17.0.6-linux-x64-b829.5                            lib

执行结果：
java -jar ./chat2db-server-start.jar                                                                                                                                                        
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
        at ai.chat2db.server.start.Application.main(Application.java:27)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 9 more

**无法使用java -jar 执行**

**Comment by jipengfei-jpf** [comment]
java -jar -Dloader.path=lib chat2db-server-start.jar
