### ISSUE TITLE
Bug: 对MongoDB中的表进行查询就会报错

### ISSUE THREAD

**Issue by dannisliang** [chat2db/Chat2DB#383]
### Chat2DB Version

2.0.7

### Describe the bug

java.lang.Exception: SyntaxError: Missing semicolon. (1:13)

> 1 | SELECT * FROM GivenLike
    |              ^
    at Parser._raise (all-standalone.js:734:17451)
    at Parser.raiseWithData (all-standalone.js:734:17390)
    at Parser.raise (all-standalone.js:734:16855)
    at Parser.semicolon (all-standalone.js:734:70877)
    at Parser.parseExpressionStatement (all-standalone.js:734:255879)
    at Parser.parseStatementContent (all-standalone.js:734:248270)
    at Parser.parseStatement (all-standalone.js:734:246071)
    at Parser.parseBlockOrModuleBlockBody (all-standalone.js:734:256518)
    at Parser.parseBlockBody (all-standalone.js:734:256356)
    at Parser.parseProgram (all-standalone.js:734:244837)

**Comment by chenxian01** [comment]
The prompt is obvious, missing semicolon. Please add semicolon at the end of your each sql and retry.
