### ISSUE TITLE
Bug:Mongodb查询依然显示错误 

### ISSUE THREAD

**Issue by dannisliang** [chat2db/Chat2DB#422]
### Chat2DB Version

2.0.10

### Describe the bug

在连接mongodb后执行以下查询语句，依然还是会报错，
SELECT * FROM AccountAbnormalState;

java.lang.Exception: SyntaxError: Missing semicolon. (1:13)

> 1 | SELECT * FROM AccountAbnormalState
    |              ^
    at Parser._raise (all-standalone.js:734:17451)
    at Parser.raiseWithData (all-standalone.js:734:17390)
    at Parser.raise (all-standalone.js:734:16855)
    at Parser.semicolon (all-standalone.js:734:70877)
    at Parser.parseExpressionStatement (all-standalone.js:734:255879)
    at Parser.parseStatementContent (all-standalone.js:734:248270)
    at Parser.parseStatement (all-standalone.js:734:246071)
    at Parser.parseBlockOrModuleBlockBody (all-standalone.js:734:256518)
    at Parser.parseBlockBody (all-standalone.js:734:256356)
    at Parser.parseProgram (all-standalone.js:734:244837)

**Comment by gujunhk** [comment]
语法是错误的；MongoDB正确的查法：
db.AccountAbnormalState.find();
