### ISSUE TITLE
Bug: 官网最新jar包无法启动

### ISSUE THREAD

**Issue by yaoyingkang** [chat2db/Chat2DB#462]
### Chat2DB Version

2.0.012

### Describe the bug

deepin v20
jdk:17
命令: sudo /usr/lib/jdk17/bin/java -jar chat2db-server-start.jar
报错:Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at ai.chat2db.server.start.Application.<clinit>(Application.java:30)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

**Comment by shanhexi** [comment]
java -jar  -Dloader.path=/lib -Dchatgpt.apiKey=xxxxx chat2db-server-start.jar  应该是没加 -Dloader.path=/lib

**Comment by yaoyingkang** [comment]
> java -jar -Dloader.path=/lib -Dchatgpt.apiKey=xxxxx chat2db-server-start.jar 应该是没加 -Dloader.path=/lib

谢谢提醒  sudo /usr/lib/jdk17/bin/java -jar -Dloader.path=./lib chat2db-server-start.jar 运行此命令才行  然而端口与官网不符合  启动端口为 http://127.0.0.1:10821/   官网说明文档为 http://127.0.0.1:10824/

**Comment by shanhexi** [comment]
jiaju,这个官网文档端口号写的有问题？

**Comment by zanglikun** [comment]
java -jar -Dloader.path=/lib chat2db-server-start.jar

Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at ai.chat2db.server.start.Application.<clinit>(Application.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

**Comment by yaoyingkang** [comment]
> java -jar -Dloader.path=/lib chat2db-server-start.jar
> 
> Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory at ai.chat2db.server.start.Application.(Application.java:30) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466) Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

应该是/usr/lib/jdk17/bin/java -jar -Dloader.path=./lib chat2db-server-start.jar  路径应该是相对路径 不是根目录下的路径

**Comment by shanhexi** [comment]
已发布3.0.0版本 已经修复
