### ISSUE TITLE
Bug: jar包启动报错

### ISSUE THREAD

**Issue by zqxvip** [chat2db/Chat2DB#522]
### Chat2DB Version

2.0.13

### Describe the bug

java -jar chat2db-server-start.jar 
从官网下载的jar包  
本机 是linux  fedora操作系统 jdk版本 17 
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at ai.chat2db.server.start.Application.<clinit>(Application.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 9 more

**Comment by shanhexi** [comment]
启动命令不正确，可以看下redme
