### ISSUE TITLE
Bug: openAI无法使用

### ISSUE THREAD

**Issue by LynnLLY** [chat2db/Chat2DB#901]
### Chat2DB Version

last

### Describe the bug

 SQL input: 解锁
2023-12-01 09:27:18.512  INFO 26510 --- [OkHttp https://api.openai.com/...] .s.w.a.c.a.o.l.OpenAIEventSourceListener.37 :  | OpenAI建立sse连接...
2023-12-01 09:27:18.512  INFO 26510 --- [OkHttp https://api.openai.com/...] .s.w.a.c.a.o.l.OpenAIEventSourceListener.46 :  | OpenAI返回数据：{"id":"chatcmpl-8QmbGSjdjsNl6oZquItW2UfZL2wmQ","object":"chat.completion.chunk","created":1701394038,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null}]}
2023-12-01 09:27:18.516 ERROR 26510 --- [OkHttp https://api.openai.com/...] .s.w.a.c.a.o.l.OpenAIEventSourceListener.101 :  | OpenAI  sse连接异常data：

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "system_fingerprint" (class ai.chat2db.server.web.api.controller.ai.response.ChatCompletionResponse), not marked as ignorable (6 known properties: "usage", "choices", "created", "model", "id", "object"])
 at [Source: (String)"{"id":"chatcmpl-8QmbGSjdjsNl6oZquItW2UfZL2wmQ","object":"chat.completion.chunk","created":1701394038,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null}]}"; line: 1, column: 156] (through reference chain: ai.chat2db.server.web.api.controller.ai.response.ChatCompletionResponse["system_fingerprint"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2224)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1709)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1687)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at ai.chat2db.server.web.api.controller.ai.openai.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:58)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

2023-12-01 09:27:18.523  INFO 26510 --- [http-nio-0.0.0.0-10824-exec-1] a.chat2db.server.start.log.EasyLogSink  .73 :  | http : GET|/api/ai/chat?message=%E8%A7%A3%E9%94%81&promptType=NL_2_SQL&dataSourceId=5&databaseName=ccp_cem&tableNames=sys_user|1881||text/event-stream:[8]
2023-12-01 09:27:18.523  INFO 26510 --- [http-nio-0.0.0.0-10824-exec-1] a.c.s.w.a.controller.ai.ChatController  .531 :  | 2023-12-01T09:27:18.523433, uid#OPENAI5689dee4-1d4d-4029-84e0-31f3c9106fd1, on completion

**Comment by LynnLLY** [comment]
有没有人呀，大家的openai都能用吗？？

**Comment by mrshawco** [comment]
我也报这个错误

**Comment by tmlx1990** [comment]
等3.1.0发布吧。openai改了返回数据。等新版本发布了再试试。
