### ISSUE TITLE
Bug: chatgpt interface return value parsing exception

### ISSUE THREAD

**Issue by HQ-Q** [chat2db/Chat2DB#905]
### Chat2DB Version

Chat2DB v3.0.14

### Describe the bug

OpenAI returns data:{"id":"chatcmpl-8Qtm2i1L3NpBRRYmP96VnoTqQ0J3Z","object":"chat.completion.chunk","created":1701421614,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null}]}
2023-12-01 17:06:54.728 ERROR 10296 --- [OkHttp https://api.openai.com/...] .s.w.a.c.a.o.l.OpenAIEventSourceListener.101 :  | OpenAI  sse连接异常data：

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "system_fingerprint" (class ai.chat2db.server.web.api.controller.ai.response.ChatCompletionResponse), not marked as ignorable (6 known properties: "usage", "choices", "created", "model", "id", "object"])
 at [Source: (String)"{"id":"chatcmpl-8Qtm2i1L3NpBRRYmP96VnoTqQ0J3Z","object":"chat.completion.chunk","created":1701421614,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null}]}"; line: 1, column: 156] (through reference chain: ai.chat2db.server.web.api.controller.ai.response.ChatCompletionResponse["system_fingerprint"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2224)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1709)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1687)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at ai.chat2db.server.web.api.controller.ai.openai.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:58)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.
